WITH H_USER 
    AS 
    (
        SELECT HOST_ID
        FROM PLACES
        GROUP BY HOST_ID
        HAVING COUNT(ID) >= 2
    )

SELECT ID,
       NAME,
       HOST_ID
FROM PLACES
WHERE HOST_ID IN (SELECT HOST_ID FROM H_USER)
ORDER BY ID;