WITH HIST AS (
    SELECT CAR_ID, HISTORY_ID, MONTH(START_DATE) MONTH
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE YEAR(START_DATE) = 2022 
    AND MONTH(START_DATE) BETWEEN '08' AND '10'
), HIST_LIMIT AS (
    SELECT CAR_ID
    FROM HIST
    GROUP BY CAR_ID
    HAVING COUNT(HISTORY_ID) >= 5
)
SELECT MONTH, CAR_ID, COUNT(HISTORY_ID) RECORDS
FROM HIST
WHERE CAR_ID IN (SELECT CAR_ID FROM HIST_LIMIT)
GROUP BY MONTH, CAR_ID 
HAVING COUNT(HISTORY_ID) > 0
ORDER BY MONTH, CAR_ID DESC;