WITH CTE as (
SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE DURATION_TYPE like '30일 이상'
)

SELECT B.CAR_ID, A.CAR_TYPE, round(((A.daily_fee - ((A.daily_fee)*(Q.DISCOUNT_RATE*0.01)))*30)) as FEE
FROM CAR_RENTAL_COMPANY_CAR AS A
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS B ON A.CAR_ID = B.CAR_ID
JOIN CTE as Q ON A.CAR_TYPE = Q.CAR_TYPE
WHERE Q.CAR_TYPE IN ('세단','SUV')
AND ((A.daily_fee - ((A.daily_fee)*(Q.DISCOUNT_RATE*0.01)))*30) >= 500000 AND ((A.daily_fee - ((A.daily_fee)*(Q.DISCOUNT_RATE*0.01)))*30) < 2000000
AND NOT EXISTS (
    SELECT NULL
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS C
    WHERE B.CAR_ID = C.CAR_ID
    AND (
        (C.start_date <= '2022-11-30' AND C.end_date >= '2022-11-01')
        OR (C.start_date >= '2022-11-01' AND C.end_date <= '2022-11-30')
    )
)
GROUP BY A.CAR_ID
ORDER BY FEE desc, A.CAR_TYPE asc, B.CAR_ID desc