WITH SUB_YEAR_MAX_SIZE AS
(
  SELECT
    MAX(ed.SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY,
    YEAR(ed.DIFFERENTIATION_DATE) AS DIFF_YEAR
  FROM ECOLI_DATA AS ed
  GROUP BY YEAR(ed.DIFFERENTIATION_DATE)
)

SELECT
  YEAR(ed.DIFFERENTIATION_DATE) AS YEAR,
  (syms.MAX_SIZE_OF_COLONY - ed.SIZE_OF_COLONY) AS YEAR_DEV,
  ed.ID
FROM ECOLI_DATA AS ed
INNER JOIN SUB_YEAR_MAX_SIZE AS syms ON YEAR(ed.DIFFERENTIATION_DATE) = syms.DIFF_YEAR
ORDER BY YEAR ASC, YEAR_DEV ASC;