WITH JOIN_2021 AS (
    SELECT COUNT(*) USERS FROM USER_INFO
    WHERE YEAR(JOINED) = 2021),

PUCHASED AS (SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT(A.USER_ID)) AS PUCHASED_USERS FROM ONLINE_SALE A
    JOIN (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021) B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR, MONTH)

SELECT P.YEAR, P.MONTH, P.PUCHASED_USERS, ROUND(P.PUCHASED_USERS/J.USERS,1) AS PUCHASED_RATIO
FROM PUCHASED P, JOIN_2021 J
ORDER BY YEAR, MONTH