WITH 기간계산 AS (
    SELECT HISTORY_ID 기록ID
    , DAILY_FEE 일일이용료
    , CAST(DATEDIFF(END_DATE,START_DATE)+1 AS UNSIGNED) 기간
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 기록DB
    INNER JOIN CAR_RENTAL_COMPANY_CAR 차DB
    ON 기록DB.CAR_ID = 차DB.CAR_ID AND CAR_TYPE = '트럭'
), 총계산 AS(
SELECT 기록ID, 일일이용료*기간*(1-IFNULL(할인율,0)*0.01) 총금액_유리
FROM 기간계산
LEFT JOIN (
  SELECT DISCOUNT_RATE 할인율, DURATION_TYPE 기간유형
  FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
  WHERE CAR_TYPE = '트럭'
) 할인정보
ON CASE
    WHEN 기간>=90 THEN 기간유형 = '90일 이상'
    WHEN 기간>=30 THEN 기간유형 = '30일 이상'
    WHEN 기간>=7 THEN 기간유형 = '7일 이상'
END
)
SELECT 기록ID HISTORY_ID, CAST(총금액_유리 AS UNSIGNED) FEE
FROM 총계산
ORDER BY 총금액_유리 DESC, HISTORY_ID DESC;