SELECT II.ITEM_ID, 
       ITEM_NAME, 
       RARITY
FROM ITEM_INFO AS II
LEFT JOIN ITEM_TREE AS IT ON II.ITEM_ID = IT.ITEM_ID
WHERE II.ITEM_ID NOT IN (SELECT DISTINCT PARENT_ITEM_ID
                         FROM ITEM_TREE
                         WHERE PARENT_ITEM_ID IS NOT NULL)
ORDER BY ITEM_ID DESC