SELECT U.USER_ID, U.NICKNAME, USR_TOTAL.TOTAL_SALES
FROM USED_GOODS_USER U
JOIN (
    SELECT WRITER_ID, SUM(PRICE) AS TOTAL_SALES
    FROM USED_GOODS_BOARD
    WHERE STATUS = "DONE"
    GROUP BY WRITER_ID
) USR_TOTAL ON U.USER_ID = USR_TOTAL.WRITER_ID
WHERE USR_TOTAL.TOTAL_SALES >= 700000
ORDER BY USR_TOTAL.TOTAL_SALES ASC;



