-- 코드를 입력하세요
SELECT TITLE, BOARD_ID, REPLY_ID, 
       R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY R USING (BOARD_ID)
WHERE YEAR(B.CREATED_DATE) = 2022 AND MONTH(B.CREATED_DATE)= 10
ORDER BY R.CREATED_DATE, TITLE;