 SELECT E.ID
 FROM ECOLI_DATA E
 LEFT JOIN ECOLI_DATA P
 ON E.PARENT_ID = P.ID
 LEFT JOIN ECOLI_DATA PP
 ON P.PARENT_ID = PP.ID
 LEFT JOIN ECOLI_DATA PPP
 ON PP.PARENT_ID = PPP.ID
 WHERE PP.ID IS NOT NULL AND PPP.ID IS NULL
 ORDER BY E.ID ASC